# Generated by Django 2.2.1 on 2019-06-28 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('ref', models.CharField(max_length=80, verbose_name='Unique product reference')),
                ('price_range', models.CharField(max_length=80, verbose_name='Price range (briefly)')),
                ('ethical', models.BooleanField(default=False, verbose_name='Ethical product')),
                ('stock_service', models.BooleanField(default=False)),
                ('small_quantities', models.BooleanField(default=False)),
                ('supply_ability', models.IntegerField(blank=True, null=True)),
                ('moq', models.IntegerField(default=0, verbose_name='Minimum Order Quantity')),
                ('lead_time_sampling', models.IntegerField(choices=[(1, '1 week'), (2, '2 weeks'), (3, '3 weeks'), (4, '4 weeks')], default=4, verbose_name='Lead Time for Sampling')),
                ('lead_time_production', models.IntegerField(choices=[(1, '1 week'), (2, '2 weeks'), (3, '3 weeks'), (4, '4 weeks'), (5, '5 weeks'), (6, '6 weeks'), (7, '7 weeks'), (8, '8 weeks'), (9, '9 weeks'), (10, '10 weeks'), (11, '11 weeks'), (12, '12 weeks')], default=8, verbose_name='Lead Time for Production')),
                ('size_w', models.IntegerField(blank=True, null=True, verbose_name='Width (mm)')),
                ('size_h', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('size_d', models.IntegerField(blank=True, null=True, verbose_name='Depth')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Collection', verbose_name='Collection')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.Org', verbose_name='Supplier organisation')),
                ('sector', models.ForeignKey(limit_choices_to={'taxonomy': True}, on_delete=django.db.models.deletion.PROTECT, to='product.Concept', verbose_name='Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Taxonomies',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Concept')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Taxonomy'),
        ),
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together={('slug', 'taxonomy')},
        ),
    ]
