# Generated by Django 2.2.1 on 2019-06-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sector',
            field=models.ForeignKey(limit_choices_to={'parent__slug': 'sectors', 'taxonomy__slug': 'fs'}, on_delete=django.db.models.deletion.PROTECT, to='product.Concept', verbose_name='Sector'),
        ),
    ]
