# Generated by Django 2.2.1 on 2019-06-25 22:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Operation name')),
                ('address1', models.CharField(max_length=50, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address 2')),
                ('town', models.CharField(blank=True, max_length=30, null=True, verbose_name='Town')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('country', models.CharField(max_length=3, verbose_name='Country Code')),
                ('phone', models.CharField(max_length=30)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'org_org',
            },
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Account User',
                'verbose_name_plural': 'Supplier Account Users',
            },
        ),
        migrations.AddField(
            model_name='org',
            name='users',
            field=models.ManyToManyField(through='org.OrgUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
